### ISSUE TITLE
Peer Review Notes

### ISSUE THREAD

**Issue by khbunyan** [UBC-MDS/group10-worldcovid-dashpython#37]

**Comment by khbunyan** [comment]
# DSCI532-peer-review

1. Open an issue with the name of your group and app
Use this template:

---
### To complete by the group
* Name of the app:  
* Link to the repo in milestone2:  
* Link to the `proposal.md` file where it is the description of the persona and scenario:  

---

2. Review the group that is one number ahead of your group's number. For example, if you are group 5, review group 6. If you are group 30, review group 1.
Paste your answers in the issue of the group assigned.

---
### To complete by the group reviewing:

**Persona**
* Provide 3 pieces of constructive feedback that could help the app to be better suited to the scenario it was designed for
* Provide 3 pieces of constructive feedback that could help the app to be better suited to the user(persona) it was designed for

**Frontend / layout**
* Is the text (plot labels / titles / subtitles) easy to read? 
* Are the plots selected appropiated for the data? Can you think of other alternatives or improvements for the plots regarding interactivity/reactivity or plot selection?
* Was the dashboard organized in a way that was easy to read (columns / rows) or you would suggest a change in this sense?
* Would you prefer including tabs / navbars to improve the navigation or you think it is better to visualize everything in one screen by the nature of the content?
* Are the plots or other images described properly for the persona described?

**Backend**
* Are the options that you can select in the widgets working fine or have you found some cases where it is not working?
* If there are interactive plots: are the labels clear and easy to understand?

**Documentation**
* Was the documentation easy to understand from the `README.md` how to use the app? How could the documentation be improved?
* Was the app intuitive to use without reading the documentation? What information could be good to include? 

**Indicate something you would like to include in your own app after reviewing this one**

---

**Comment by khbunyan** [comment]
Kristin's comments:

---
### To complete by the group reviewing:

**Persona**
**Provide 3 pieces of constructive feedback that could help the app to be better suited to the scenario it was designed for**
- Your interface is beautiful; however I found the plot "Total Deaths and Earthquake Magnitude per Event" is a bit small, especially when you add 6+ countries in the "Countries of Interest" filter. I would use more of that empty space to make these a bit bigger so it's easier to decipher what's being shown when the volume gets higher; or alternatively as opposed to using the log-scale you might consider to reflect the actual death numbers on your y axes for a more widely intuitive visualization.  
- I would make a similar comment for the map as well, the "Tsunami Origin" dots are very small and it's hard to navigate your cursor to a specific one when there are many. For example, Japan has many earthquakes, it's hard to distinguish between them for certain time periods. I would consider adding more to the tooltip here, such as "year" so it's easier to see the occurrence of the tsunami when instances from multiple years are displayed. I think someone in the scenario you've laid out in your proposal would benefit from that.
-  I would add a gradient colours to the "Tsunami Origin" dots that reflect magnitudes so that the dots are more distinct from one another. When many dots are overlapping it might make it easier to see them individually and someone in your described scenario might have an easier time navigating this way.

**Provide 3 pieces of constructive feedback that could help the app to be better suited to the user(persona) it was designed for**
- It would be helpful if you provide a link to the raw data either in your repo README as a brief introduction of where the data is sourced, or as a reference on your dashboard. Putting myself in the shoes of a female-technologist for your target audience Victoria, I would probably want to be able to easily access the raw data that I'm searching through and so I can record/save/play with the information that I'm curious about.
- A lot of insurance analysis is based on expected events or averages. Something like the "average magnitude" or "average deaths" in the countries tooltip on the map potentially would add more contexts to this plot, which could be useful for your target audiences. 
- ![Screen Shot 2022-03-08 at 7 59 37 PM](https://user-images.githubusercontent.com/69618055/157370209-61994cea-c384-4b84-99c3-00d789a3906e.png)
- I think a filter for magnitude would be really helpful in your dashboard. Many small earthquakes happen often (a lot in BC!), but are probably of little interest to an insurance company because they don't cause much damage. If I were Victoria, I would want to understand how much money my company is potentially paying out for damages, and so I probably care more about the larger magnitudes; it would be nice to filter for that.  

**Frontend / layout**
* Is the text (plot labels / titles / subtitles) easy to read? 
    - Other than the sizing comments noted above, your dashboard is very clean and aesthetically pleasing.
    - The titles are all easy to interpret and cleanly written. My only comment would be to capitalize "country" in the "10 Most Intense...." plot
* Are the plots selected appropriated for the data? Can you think of other alternatives or improvements for the plots regarding interactivity/reactivity or plot selection?
     - Yes, I believe so. In your proposal it mentioned being able to filter by month, day, etc. Adding a filter to adjust the granularity of the time data would be a great addition as it would likely reveal a lot in terms of what affects the insurance company.
     - Per my comment above, adding a filter for magnitude and some more contexts to your country tooltip would improve the dashboard.
* Was the dashboard organized in a way that was easy to read (columns / rows) or you would suggest a change in this sense?
     - Yes it was! I think the design and the layout are beautiful. I would only comment about the sizing, as previously noted, and the y-axis/grid lines in the "Total Deaths...." plot. They are a little oddly spaced out with some smaller gaps and some larger ones. I think this is due to the log scale, but if you're not familiar with log it might be hard to understand right away.
* Would you prefer including tabs / navbars to improve the navigation or you think it is better to visualize everything in one screen by the nature of the content?
     - I think having everything in one screen looks great, I wouldn't change that. It's great for comparison across plots.
* Are the plots or other images described properly for the persona described?
     - Yes! Everything is clearly noted, and intuitive to understand.

**Backend**
* Are the options that you can select in the widgets working fine or have you found some cases where it is not working
    - Everything works for me :tada:

* If there are interactive plots: are the labels clear and easy to understand?
    - As noted above, I would add the "year" to the "Tsunami Origin" tooltips, and a magnitude gradient so the dots are more distinct from each other. Otherwise it's great!

**Documentation**
* Was the documentation easy to understand from the `README.md` how to use the app? How could the documentation be improved?
    - Proposal: the dashboard sketch image is broken and there are a few words that are in square brackets in the "Research Questions and Usage Scenarios" section
    - ![Screen Shot 2022-03-08 at 7 33 44 PM](https://user-images.githubusercontent.com/69618055/157367676-7ae35357-b0f8-42e2-9a94-648790cc2d46.png)
    - Installation instructions via bash gave me an error. First I ran `git clone https://github.com/UBC-MDS/tsunami-events-dashboard-python.git`, then `pip install -r requirements.txt` and got:
        - <img width="749" alt="Screen Shot 2022-03-08 at 7 36 27 PM" src="https://user-images.githubusercontent.com/69618055/157367929-143c80df-35d5-4e1d-a470-aa9f0e3104fb.png">
        - Perhaps you're missing a dependancy for the map in your .txt?
    - I would expand on your contributing section a bit further to instruct people how exactly they can contribute to your dashboard if they would like to.
    - Consider adding a gif to show how the dashboard works
    - I would reorganize the "Description of the App Interface" with bullet points so its easier to reference when using the dashboard.

* Was the app intuitive to use without reading the documentation? What information could be good to include? 
    - Yes, the app is super easy to use and very cool at looking. I'm really impressed with this aspect of your project. I have no comments for this section.

**Indicate something you would like to include in your own app after reviewing this one**
* I really loved the distinct borders that you included for all of your plots. The separation of the space with a side bar to navigate makes the dashboard being visually presented. This was really well done, I had to dig to find things to suggest improvement on. I had a great time exploring Tsunami stats! Thanks team.
---

**Comment by thomassiu** [comment]
Hi Kristin,

Thanks and it was so detailed! Just one minor point on the first item, that the app probably can zoom into the North America zone by default as I believe the user probably focuses on North America / BC insurance clients.

**Comment by khbunyan** [comment]
Thank you @thomassiu I've added your comment:

https://github.com/UBC-MDS/DSCI532-peer-review/issues/12#issuecomment-1062562918
