### ISSUE TITLE
Software Comparison Notes

### ISSUE THREAD

**Issue by khbunyan** [UBC-MDS/group10-worldcovid-dashpython#38]

**Comment by Kingslin0810** [comment]
[group_10.md](https://github.com/UBC-MDS/group10-worldcovid-dashpython/files/8229666/group_10.md)

I made the first stub of the software comparison for our group; any comments are welcomed.

**Comment by thomassiu** [comment]
I've made my version here:

https://github.com/thomassiu/dash-tableau-shiny_comparison/blob/main/group_10.md

**Comment by Kingslin0810** [comment]
Pull request is created [here](https://github.com/UBC-MDS/dash-tableau-shiny_comparison/pull/13)
You can view it [here](https://github.com/Kingslin0810/dash-tableau-shiny_comparison/blob/main/group_10.md)
